# Generated by Django 6.0.4 on 2026-04-17 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('appointment_date', models.CharField(max_length=50)),
                ('appointment_time', models.CharField(max_length=50)),
                ('appointment_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('chờ khám', 'chờ khám'), ('đã khám', 'đã khám'), ('đã hủy', 'đã hủy')], default='chờ khám', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
