# Generated by Django 6.0.4 on 2026-04-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
